### ISSUE TITLE
Add demo video (embedded) to Demo Page + other small copy changes

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1424]
https://app.asana.com/0/1204221566683177/1204811565198652/f
Hello :) we need to do these couple of changes on demo page!
Let me know if you need anything

Add video section:
https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?type=design&node-id=3777%3A57879&t=xWEfm2xMvNFmFn5H-1

Video: 
https://www.youtube.com/watch?v=hVktdWfyBuU

Copy changes: 
1. Header: Fingerprint Pro Demo → **Fingerprint Demo (without "Pro")**
2. visitorID → **visitor ID**
3. visitorIDs → **visitor IDs**
4. Get a demo section header: Get a Demo → **Get custom demo** 

THANK YOU

**Comment by sabrinazimet** [comment]
thank you!!!!

1 - I think a couple of visitorIDs were missed, is that possible?

2 - Can we take out the outline/border from the video, it makes a weird effect when combined with the embedded because it has a black outline already

3 - this was missed: Get a demo section header: **Get a Demo → Get custom demo**

**Comment by natapg** [comment]
1- I made the changes in another PR related to the ticket that you created before -> https://fingerprint-com-git-fix-rename-visitorid-fp-pro.vercel.app/demo/ so I don't focus on that on this PR
2- sure!
3- that's weird, I made that change, let me check
![image](https://github.com/fingerprintjs/fingerprint.com/assets/47128448/b5c2c790-33d0-426d-b671-6c4720ae5727)

**Comment by natapg** [comment]
done

**Comment by sabrinazimet** [comment]
<img width="642" alt="Screen Shot 2023-06-21 at 12 02 14" src="https://github.com/fingerprintjs/fingerprint.com/assets/111449971/d97accff-5661-446e-882b-14f9dbbd3a9b">
I still see it like this, but it may be a PR problem I guess???? thank you :)

**Comment by natapg** [comment]
nice, I'll deploy it now :)
